import { Inter, Open_Sans, Montserrat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter", });
const openSans = Open_Sans({ subsets: ["latin"], variable: "--font-opensans", });
const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-montserrat", });

export const metadata = {
  title: "Astronova Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${openSans.variable} ${montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
